parameters:
#    acme_page.example.class: Acme\PageBundle\Example

services:
#    acme_page.example:
#        class: %acme_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
